### PR TITLE
Wrap to 80 cols and remove blank lines in figures

### LINKED ISSUE #83: Wrap lines
It would make it a lot easier to read and edit markdown (and preview on github)  if we wrap lines to sensible column size (I use the "80 or 72 for long paragraphs" principle myself, and for the letsencrypt client). Thoughts? If you agree then please let me know and I'll prepare necessary PR. Probably it's best to pull in other PRs first, though.

### PR DESCRIPTION
**Pull request by bifurcation**
Fixes #83

### CODE REVIEW

**Comment by kuba** [comment]
I'm happy to see #83 coming through. :)

**Comment by ekr** [comment]
This doesn't seem worth reviewing. I'm prepared to trust you got this right if Travis passes on it.

**Comment by kuba** [comment]
@ekr, I believe rich diff shows no changes: https://github.com/letsencrypt/acme-spec/pull/179/files?short_path=2e5a10b#diff-2e5a10b3cfb1002733218cd4472b40a4

**Comment by bifurcation** [comment]
@ekr That was my plan.  Just waiting on Travis.

**Comment by bifurcation** [comment]
@kuba See, I can learn from my mistakes!

**Comment by jsha** [comment]
LGTM

**Pull request merged**
