### PR TITLE
Update GitHub Pages

### LINKED ISSUE #76: Update GitHub Pages to v02.
https://letsencrypt.github.io/acme-spec/ is still at v00, and draft is already v02.

### PR DESCRIPTION
**Pull request by kuba**
Generated with `make gh-pages`. Temporarily fixes #76, but please consider fixing #78 for the long term. You can view it at http://kuba.github.io/acme-spec/

### CODE REVIEW

**Comment by kuba** [comment]
Actually, it seems like the output is broken (equally likely source markdown might be broken). Hold on with pulling this until I resolve.

**Comment by kuba** [comment]
Indeed, with the same setup, `git checkout v00; make html` produces valid output => another bug.

**Comment by kuba** [comment]
Once you pull #80 I will update this PR.

**Comment by martinthomson** [comment]
Yeah, I think that #78 is a better solution here.

**Comment by kuba** [comment]
@jsha This is now up to date with 155872c1b7bae0a090b6e8d9cba66411d1583337, with fixed output. :)

**Pull request merged**
