### PR TITLE
Versioning

### PR DESCRIPTION
**Pull request by pde**
Version protocol and disambiguate example domains:

 - Add protocol version to the hostname, per:
   letsencrypt/boulder#60

 - Avoid using example.com for both the client and the server's domains; move
   the server to example.ca.

### CODE REVIEW

**Comment by martinthomson** [comment]
I think that the versioning changes here are strictly bad.

Attaching semantics to any part of the URL violates the principles in RFC 7230.

Now, part of the reason for those guidelines is so that boulder can choose to structure its URL-space anyway it sees fit.  And the protocol structure here means that - though it might need to make some sort of commitment to the entry point - none of the other URLs are baked into a client; the server can change its structure as it sees fit.

That said, I don't believe that it's a good idea to have boulder bake in a version number.  For instance, web services at Mozilla generally just spin up a new server name for a new version of a protocol.  It's much cleaner that way.

I think that your changes to names might be OK.  `client.example` and `server.example` are classics if you want to avoid being overly Canadian (I hear that can be a problem).

**Comment by pde** [comment]
> web services at Mozilla generally just spin up a new server name for a new version of a protocol. It's much cleaner that way.

I'm slightly confused.  The above is exactly what the pull request does, it just makes it clear what those server names will be.

**Comment by martinthomson** [comment]
It codifies the practice:

> The leftmost label of the server's domain name contains the version of the protocol which that server speaks [...]

That's saying that this method of handling versions is *the* method, as decided by (in this case) the IETF.  I'd recommend taking a look at [Section 2.2 of RFC 7320](https://tools.ietf.org/html/rfc7320#section-2.2) for this.

(Apologies for fat-fingering the name of RFC 7320, it transposes into 7230 too easily.  I can understand how that might be confusing.)

**Comment by pde** [comment]
So if I understand you correctly, you're saying that we *should* probably use hostnames like v01.api.example.ca in deployment, but that those shouldn't be codified in the spec?

**Comment by martinthomson** [comment]
What you do in your deployment is up to you.  Don't make me do the same though.

I tend to think that version numbers in domain names or URIs is pointless.  Call it `acme.example.com` and leave it at that.  If you need a new version and you can't (or don't want to) have the same server talk two versions, call it `acme2.example.com` or `acmii.example.com`.  But some people like the warm sense of safety it provides (or something).

**Comment by bifurcation** [comment]
@martinthomson is right here.  This is a deployment consideration, not for a spec requirement.  If you want to do anything here, please rewrite as a general recommendation ("Multiple versions can be run on different URLs"), not a requirement.

**Comment by pde** [comment]
@bifurcation Seems I had a month-old commit lying around to do just that.

**Comment by bifurcation** [comment]
The right answer here is basically what is suggested in #43 -- if anything is to be done here, it should just clarify that each URL handles exactly one version of the protocol.

**Pull request closed without merging**
