### PR TITLE
Replace SimpleHTTPS with SimpleHTTP.

### LINKED ISSUE #108: Re-add Simple HTTP
Since Simple HTTPS appears to have some virtual-hosting related vulnerabilities that Simple HTTP doesn't, the spec should include Simple HTTP.

### LINKED ISSUE #124: Remove requirement for self-signed cert in simpleHttps
There's no reason for the requirement that the simpleHttps server present a self-signed certificate (cf. #108), and it breaks some use cases, e.g., when the server has a cert from another CA.  So we should remove this restriction.

### PR DESCRIPTION
**Pull request by jsha**
Fixes #108.
Fixes #124.

cc @bifurcation @pde for code review.

### CODE REVIEW

**Comment by pde** [comment]
The big question is whether Simple HTTPS should stay in the spec in case anyone wants to use it in the future.  The possible vhost issues argue against it, though.

**Comment by jsha** [comment]
Agreed, I think we should define just Simple HTTP in the spec for now.

**Comment by bifurcation** [comment]
I disagree with adding client-chosen ports right now.  We should focus on the core requirement here, which is default ports.  I have sketched out a potential solution in the client-chosen-ports branch, but I'm not comfortable enough with the security analysis to add it to the spec / boulder at this time.

**Comment by bifurcation** [comment]
That said, for forward compatibility with that branch, I will rename "nonsecure" to "tls".  It isn't appropriate to use "scheme", because it's not like we're going to support "imaps" or something like that.  This is simple**Http**; the only question is TLS or not.

**Pull request merged**
